name: Deploy to github pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    environment: github-pages
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build --if-present
        env:
          VUE_APP_API_TOKEN: ${{ secrets.VUE_APP_API_TOKEN }}
          VUE_APP_API_URL: ${{ secrets.VUE_APP_API_URL }}

      - name: deploy files
        uses: JamesIves/github-pages-deploy-action@4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
          clean: true
